import test from 'ava-spec';
import ObjectFixture from '../fixtures/object.fixture';
import common from '../../lib/common';

test('lib/common.typeOf', t => {
	t.is(toString.call(common.typeOf), '[object Function]');
	t.is(common.typeOf((() => arguments)()), 'Arguments');
	t.is(common.typeOf(arguments), 'Arguments');
	t.is(common.typeOf('ab'), 'String');
	t.is(common.typeOf(new String('foo')), 'String');
	t.is(common.typeOf(/^./g), 'RegExp');
	t.is(common.typeOf(new RegExp('foo')), 'RegExp');
	t.is(common.typeOf(10000), 'Number');
	t.is(common.typeOf(new Number(42)), 'Number');
	t.is(common.typeOf({name: 1}), 'Object');
	t.is(common.typeOf({}), 'Object');
	t.is(common.typeOf(Object.create(null)), 'Object');
	t.is(common.typeOf(new ObjectFixture()), 'ObjectFixture');
	t.is(common.typeOf([]), 'Array');
	t.is(common.typeOf([1, 2]), 'Array');
	t.is(common.typeOf(new Array()), 'Array');
	t.is(common.typeOf(true), 'Boolean');
	t.is(common.typeOf(false), 'Boolean');
	t.is(common.typeOf(new Boolean(true)), 'Boolean');
	t.is(common.typeOf(null), 'Null');
	t.is(common.typeOf(undefined), 'Undefined');
	t.is(common.typeOf(Symbol), 'Function');
	t.is(common.typeOf(Symbol('bar')), 'Symbol');
	t.is(common.typeOf(String), 'Function');
	t.is(common.typeOf(Boolean), 'Function');
	t.is(common.typeOf(Number), 'Function');
	t.is(common.typeOf(RegExp), 'Function');
	t.is(common.typeOf(TypeError), 'Function');
	t.is(common.typeOf(Error), 'Function');
	t.is(common.typeOf(Object), 'Function');
	t.is(common.typeOf(Array), 'Function');
	t.is(common.typeOf(Boolean), 'Function');
	t.is(common.typeOf(Date), 'Function');
	t.is(common.typeOf(ObjectFixture), 'Function');
	t.is(common.typeOf(function () {}), 'Function');
	t.is(common.typeOf(new Function()), 'Function');
	t.is(common.typeOf(function * () {}), 'GeneratorFunction');
	t.is(common.typeOf(new Map()), 'Map');
	t.is(common.typeOf(new WeakMap()), 'WeakMap');
	t.is(common.typeOf(new Set()), 'Set');
	t.is(common.typeOf(new WeakSet()), 'WeakSet');
	t.is(common.typeOf(new Int8Array()), 'Int8Array');
	t.is(common.typeOf(new Uint8Array()), 'Uint8Array');
	t.is(common.typeOf(new Uint8ClampedArray()), 'Uint8ClampedArray');
	t.is(common.typeOf(new Int16Array()), 'Int16Array');
	t.is(common.typeOf(new Uint16Array()), 'Uint16Array');
	t.is(common.typeOf(new Int32Array()), 'Int32Array');
	t.is(common.typeOf(new Uint32Array()), 'Uint32Array');
	t.is(common.typeOf(new Float32Array()), 'Float32Array');
	t.is(common.typeOf(new Float64Array()), 'Float64Array');
	t.is(common.typeOf(new Date()), 'Date');
	t.is(common.typeOf(ArrayBuffer), 'Function');
	t.is(common.typeOf(new ArrayBuffer(4)), 'ArrayBuffer');
	t.is(common.typeOf(Buffer), 'Function');
	t.is(common.typeOf(new Buffer(3)), 'Uint8Array');
	// t.is(common.typeOf(new Buffer('')), 'Buffer');

});

test('lib/common.writeNameFromType', t => {
	t.is(toString.call(common.writeNameFromType), '[object Function]');
	t.is(common.writeNameFromType((() => arguments)()), 'Arguments');
	t.is(common.writeNameFromType(Symbol), 'Symbol');
	t.is(common.writeNameFromType(String), 'String');
	t.is(common.writeNameFromType(RegExp), 'RegExp');
	t.is(common.writeNameFromType(Number), 'Number');
	t.is(common.writeNameFromType(TypeError), 'TypeError');
	t.is(common.writeNameFromType(Error), 'Error');
	t.is(common.writeNameFromType(Object), 'Object');
	t.is(common.writeNameFromType(Array), 'Array');
	t.is(common.writeNameFromType(Boolean), 'Boolean');
	t.is(common.writeNameFromType(Date), 'Date');
	t.is(common.writeNameFromType(null), 'Null');
	t.is(common.writeNameFromType(undefined), 'Undefined');
	t.is(common.writeNameFromType(NaN), 'Number');
	t.is(common.writeNameFromType('ab|ba', true), 'ab|ba');
	t.is(common.writeNameFromType('ab|ba'), 'String');
	t.is(common.writeNameFromType(new ObjectFixture('FixtureTest')), 'FixtureTest');
	t.is(common.writeNameFromType(ObjectFixture), 'FixtureTest');
	t.is(common.writeNameFromType([1, 2]), 'Array');
	t.is(common.writeNameFromType(/^./g), 'RegExp');
	t.is(common.writeNameFromType(10000), 'Number');
	t.is(common.writeNameFromType({name: 1}), 'Object');
	t.is(common.writeNameFromType(false), 'Boolean');
	t.is(common.writeNameFromType(new Date()), 'Date');
	t.is(common.writeNameFromType(ArrayBuffer), 'ArrayBuffer');
	t.is(common.writeNameFromType(new ArrayBuffer(4)), 'ArrayBuffer');
	t.is(common.writeNameFromType(Buffer), 'Buffer');
	t.is(common.writeNameFromType(new Buffer('ab')), 'Uint8Array');
	// t.is(common.writeNameFromType(new Buffer('ab')), 'Buffer');
});

test('lib/common.typify', t => {
	t.is(toString.call(common.typify), '[object Function]');
	t.is(common.typify('Arguments', (() => arguments)()), 'Arguments');
	t.is(common.typify([Symbol, String, Function, Object, Boolean]), 'Symbol|String|Function|Object|Boolean');
	t.is(common.typify([Symbol, String, Function, Object, Boolean,]), 'Symbol|String|Function|Object|Boolean'); // should be 'Symbol|String|Function|Object|Boolean|Undefined'
	t.is(common.typify('Symbol|String|Function|Object|Boolean', true), 'Symbol|String|Function|Object|Boolean');
	t.is(common.typify([1, 'Custom', {}]), 'Number|Custom|Object'); // <- should it be an array?
	t.is(common.typify([]), 'Array');
	t.is(common.typify(1), 'Number');
	t.is(common.typify('Custom', true), 'Custom');
	t.is(common.typify({}), 'Object');
	t.is(common.typify({name: 1}), 'Object');
	t.is(common.typify(/^./g), 'RegExp');
	t.is(common.typify(false), 'Boolean');
	t.is(common.typify(new Date()), 'Date');
	t.is(common.typify(Date), 'Date');
	t.is(common.typify(ArrayBuffer), 'ArrayBuffer');
	t.is(common.typify(new ArrayBuffer(4)), 'ArrayBuffer');
	t.is(common.typify(Buffer), 'Buffer');
	t.is(common.typify(new Buffer('ab')), 'Uint8Array');
	// t.is(common.typify(new Buffer('ab')), 'Buffer');
});

test('lib/common.constructorNameOf', t => {
	t.is(toString.call(common.constructorNameOf), '[object Function]');
	t.is(common.constructorNameOf((() => arguments)()), 'Arguments');
	t.is(common.constructorNameOf(Symbol), 'Symbol');
	t.is(common.constructorNameOf(Symbol.name), 'String');
	t.is(common.constructorNameOf(String), 'String');
	t.is(common.constructorNameOf(String.name), 'String');
	t.is(common.constructorNameOf(RegExp), 'RegExp');
	t.is(common.constructorNameOf(RegExp.name), 'String');
	t.is(common.constructorNameOf(Number), 'Number');
	t.is(common.constructorNameOf(Number.name), 'String');
	t.is(common.constructorNameOf(TypeError), 'TypeError');
	t.is(common.constructorNameOf(TypeError.name), 'String');
	t.is(common.constructorNameOf(Error), 'Error');
	t.is(common.constructorNameOf(Error.name), 'String');
	t.is(common.constructorNameOf(Object), 'Object');
	t.is(common.constructorNameOf(Object.name), 'String');
	t.is(common.constructorNameOf(Array), 'Array');
	t.is(common.constructorNameOf(Array.name), 'String');
	t.is(common.constructorNameOf(Boolean), 'Boolean');
	t.is(common.constructorNameOf(Boolean.name), 'String');
	t.is(common.constructorNameOf(Date), 'Date');
	t.is(common.constructorNameOf(Date.name), 'String');
	t.is(common.constructorNameOf(null), 'Null');
	t.is(common.constructorNameOf(undefined), 'Undefined');
	t.is(common.constructorNameOf(Infinity), 'Number');
	t.is(common.constructorNameOf(NaN), 'Number');
	t.is(common.constructorNameOf(NaN.name), 'Undefined');
	t.is(common.constructorNameOf('ab|ba'), 'String');
	t.is(common.constructorNameOf(new ObjectFixture()), 'ObjectFixture');
	t.is(common.constructorNameOf(ObjectFixture), 'ObjectFixture');
	t.is(common.constructorNameOf(ObjectFixture.name), 'String');
	t.is(common.constructorNameOf([1, 2]), 'Array');
	t.is(common.constructorNameOf(/^./g), 'RegExp');
	t.is(common.constructorNameOf(10000), 'Number');
	t.is(common.constructorNameOf({name: 1}), 'Object');
	t.is(common.constructorNameOf(false), 'Boolean');
	t.is(common.constructorNameOf(new Date()), 'Date');
	t.is(common.constructorNameOf(ArrayBuffer), 'ArrayBuffer');
	t.is(common.constructorNameOf(Buffer), 'Buffer');
	t.is(common.constructorNameOf(Buffer.name), 'String');
	t.is(common.constructorNameOf(new Buffer('ab')), 'Uint8Array');
	// t.is(common.constructorNameOf(new Buffer('ab')), 'Buffer');
});

test('lib/common.constructorOf', t => {
	t.is(toString.call(common.constructorOf), '[object Function]');
	t.is(common.constructorOf((() => arguments)()), Object);
	t.is(common.constructorOf(Symbol('foo')), Symbol);
	t.is(common.constructorOf(new String()), String);
	t.is(common.constructorOf(new RegExp('^foo')), RegExp);
	t.is(common.constructorOf(/^./g), RegExp);
	t.is(common.constructorOf(new TypeError('foo')), TypeError);
	t.is(common.constructorOf(new Error('foo')), Error);
	t.is(common.constructorOf(new Object()), Object);
	t.is(common.constructorOf({name: 1}), Object);
	t.is(common.constructorOf(new Array()), Array);
	t.is(common.constructorOf([1, 2]), Array);
	t.is(common.constructorOf(new Boolean()), Boolean);
	t.is(common.constructorOf(new Date()), Date);
	t.is(common.constructorOf(null), null);
	t.is(common.constructorOf(undefined), undefined);
	t.is(common.constructorOf(Infinity), Number);
	t.is(common.constructorOf(NaN), Number);
	t.is(common.constructorOf(10000), Number);
	t.is(common.constructorOf('ab|ba'), String);
	t.is(common.constructorOf(new ObjectFixture('FF')), ObjectFixture);
	t.is(common.constructorOf(ObjectFixture), Function);
	t.is(common.constructorOf(false), Boolean);
	t.is(common.constructorOf(new Uint8Array()), Uint8Array);
	// t.is(common.constructorOf(ArrayBuffer), ArrayBuffer);
	// t.is(common.constructorOf(Buffer), Buffer);
	t.is(common.constructorOf(new Buffer('1234')), Buffer);
});

test('lib/common.is', t => {
	t.is(toString.call(common.is), '[object Function]');
	t.is(common.is('Arguments', (() => arguments)()), true);
	t.is(common.is('Function|Array|Number', Infinity), true);
	t.is(common.is('Function|Array|Infinity', String), true);
	t.is(common.is('Function|Array', String), true);
	t.is(common.is('Function|Array', []), true);
	t.is(common.is('Function|Array', () => []), true);
	t.is(common.is('String|Function', 'pirate'), true);
	t.is(common.is([String, Function, Object, Infinity], Infinity), true);
	t.is(common.is([String, Function, Object, Infinity], Number), true);
	t.is(common.is([String, Function, Object, Infinity], 0), true);
	t.is(common.is([String, Function, Object, Boolean], 'pirate'), true);
	t.is(common.is([String.name, Function.name], 'pirate'), true);
	t.is(common.is('String|Function', () => 'pirate'), true);
	t.is(common.is([String, Function], () => 'pirate'), true);
	t.is(common.is([String.name, Function.name], () => 'pirate'), true);
	t.is(common.is('Function', () => 'pirate'), true);
	t.is(common.is(Function, () => 'pirate'), true);
	t.is(common.is(Function.name, () => 'pirate'), true);
	t.is(common.is('String', () => 'pirate'), false);
	t.is(common.is(String, () => 'pirate'), false);
	t.is(common.is(String.name, () => 'pirate'), false);
	t.is(common.is(ObjectFixture, new ObjectFixture('pirate')), true);
	t.is(common.is(ObjectFixture.name, new ObjectFixture('pirate')), true);
	t.is(common.is('Pirate', new ObjectFixture('Pirate')), true);
	t.is(common.is(undefined, undefined), true);
	t.is(common.is('undefined', undefined, true), true);
	t.is(common.is('Undefined', undefined), true);
	t.is(common.is(null, null), true);
	t.is(common.is('null', null, true), true);
	t.is(common.is('Null', null), true);
	t.is(common.is(NaN, NaN), true);
	t.is(common.is(Number, NaN), true);
	t.is(common.is(Number.name, NaN), true);
	t.is(common.is('Number', NaN), true);
});

test('lib/common.is.not', t => {
	t.is(toString.call(common.is.not), '[object Function]');
	t.is(common.is.not('Arguments', (() => arguments)()), false);
	t.is(common.is.not('Function|Array|Number', String), false);
	t.is(common.is.not('Function|Array|Number', Infinity), false);
	t.is(common.is.not('Function|Array', String), false);
	t.is(common.is.not('Function|Array', []), false);
	t.is(common.is.not('Function|Array', () => []), false);
	t.is(common.is.not('String|Function', 'pirate'), false);
	t.is(common.is.not([String, Function, Object, Boolean], 'pirate'), false);
	t.is(common.is.not([String, Function, Object, Infinity], Infinity), false);
	t.is(common.is.not([String, Function, Object, Infinity], Number), false);
	t.is(common.is.not([String, Function, Object, Infinity], 0), false);
	t.is(common.is.not([String.name, Function.name], 'pirate'), false);
	t.is(common.is.not('String|Function', () => 'pirate'), false);
	t.is(common.is.not([String, Function], () => 'pirate'), false);
	t.is(common.is.not([String.name, Function.name], () => 'pirate'), false);
	t.is(common.is.not('Function', () => 'pirate'), false);
	t.is(common.is.not(Function, () => 'pirate'), false);
	t.is(common.is.not(Function.name, () => 'pirate'), false);
	t.is(common.is.not('String', () => 'pirate'), true);
	t.is(common.is.not(String, () => 'pirate'), true);
	t.is(common.is.not(String.name, () => 'pirate'), true);
	t.is(common.is.not(ObjectFixture, new ObjectFixture('pirate')), false);
	t.is(common.is.not(ObjectFixture.name, new ObjectFixture('pirate')), false);
	t.is(common.is.not('ObjectFixture', new ObjectFixture()), false);
	t.is(common.is.not(undefined, undefined), false);
	t.is(common.is.not('undefined', undefined, true), false);
	t.is(common.is.not('Undefined', undefined), false);
	t.is(common.is.not(null, null), false);
	t.is(common.is.not('null', null, true), false);
	t.is(common.is.not('Null', null), false);
	t.is(common.is.not(Infinity, Infinity), false);
	t.is(common.is.not(Infinity, Number), true);
	t.is(common.is.not(Number, Infinity), false);
	t.is(common.is.not(NaN, NaN), false);
	t.is(common.is.not(Number, NaN), false);
	t.is(common.is.not(Number.name, NaN), false);
	t.is(common.is.not('Number', NaN), false);
});
